### ISSUE TITLE
Riffmaster Thumbstick not working

### ISSUE THREAD

**Issue by Uncraftbar** [TheNathannator/RB4InstrumentMapper#18] opened 2024-05-26 13:56 UTC
Using the program with the PDP Riffmaster works good, only 2 things that are kinda wonky.

First one isnt really a bug but more a feature request. It would be nice to get the Thumbstick working (for example for quickly activating star power) right now only pressing the thumbstick down (R3) seems to be working, the movement itself not.

I also have to restart my guitar after switching driver, but thats a whole other issue lol

**Comment by TheNathannator** [comment] 2024-05-27 06:38
The joystick *should* already work, I'll need a packet log to verify though. Can you enable packet logging, then hit Start and move the joystick around, then hit Stop and send the resulting packet log file here?

  ![image](https://github.com/TheNathannator/RB4InstrumentMapper/assets/29052821/e664f7e9-bcf3-47d6-b6bf-8b75f9f124ce)

The driver switching process is quite janky and I don't think I can really make it much smoother lol, as long as you can make it work without too much trouble I'll be satisfied. I'm unable to reproduce any of the issues people have reported with it, and I don't have a Riffmaster to properly test things with.

**Comment by Uncraftbar** [comment] 2024-05-28 16:50
I would love to, but if i enable those options, press on start (restart my guitar because it wont get picked up otherwise) the programm just "Crashes" i guess. I cant click on anything and it doesnt update, but its still working as in i get gamepad output to Yarg. Might just try a restart of my PC real quick, maybe that fixes it.

**Comment by Uncraftbar** [comment] 2024-05-28 16:58
Okay, reinstalled the program, and the joystick does now work! Maybe i wasnt running latest (i thought i was, but who knows). Still the other issues tho. Solved itself then

**Comment by TheNathannator** [comment] 2024-05-28 17:45
Oh nice!

I tried to fix that lock-up bug, but if it's still happening in the latest pre-release I'll need to look further into it. Just not sure what it's hanging on.

**Comment by TheNathannator** [comment] 2024-05-28 18:01
Made #19 to track the lock-up issue, so I'll be closing this one.

**Closed by TheNathannator** 2024-05-28 18:01 UTC
Labels: bug, enhancement
